### ISSUE TITLE
方案优化

### ISSUE THREAD

**Issue by leoparddne** [lindexi/lindexi_gd#35]
可以不用这么复杂，直接通过检测EditingModeChanged并绑定不同的光标即可实现
  private void inkCanvas_EditingModeChanged(object sender, RoutedEventArgs e)
        {

            switch (inkCanvas.EditingMode)
            {
                case InkCanvasEditingMode.None:
                    inkCanvas.Cursor = Cursors.Arrow;
                    break;
                case InkCanvasEditingMode.Ink:
                    inkCanvas.Cursor = CursorHelper.CreateCursorFromCur("/img/icon-huabi.cur");
                    break;
                case InkCanvasEditingMode.GestureOnly:
                    break;
                case InkCanvasEditingMode.InkAndGesture:
                    break;
                case InkCanvasEditingMode.Select:
                    break;
                case InkCanvasEditingMode.EraseByPoint:
                case InkCanvasEditingMode.EraseByStroke:
                    //共用一个样式
                    inkCanvas.Cursor = CursorHelper.CreateCursorFromCur("/img/icon-rubber.cur");
                    break;
                default:
                    break;
            }
        }

**Comment by lindexi** [comment]
@leoparddne 多谢
