### ISSUE TITLE
请问下透明窗口可以只在透明的部分进行穿透吗？

### ISSUE THREAD

**Issue by knota-lab** [lindexi/lindexi_gd#43]
如题，我测试了下界面上的非透明元素也穿透了，有没有办法只在透明的部分进行穿透呢

https://github.com/lindexi/lindexi_gd/tree/b26274ae2ba4b54c151b69db4e899781fb640597/RuhuyagayBemkaijearfear/RuhuyagayBemkaijearfear

**Comment by lindexi** [comment]
@zemelLeong 此方法不成
